basePath: /api/v1
definitions:
  handlers.CreateStoryRequest:
    properties:
      city:
        type: string
      country:
        type: string
      preferences:
        items:
          type: string
        type: array
      religions:
        items:
          type: string
        type: array
    type: object
  handlers.StoryResponse:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A comprehensive API for generating and managing stories with AI
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Story API
  version: "1.0"
paths:
  /story:
    post:
      consumes:
      - application/json
      description: Create a new story with the provided details
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Story creation request
        in: body
        name: story
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateStoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.StoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.StoryResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.StoryResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.StoryResponse'
      security:
      - BearerAuth: []
      summary: Create a new story
      tags:
      - stories
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
